// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    DF: typeof import('./components/DF.md')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HelloWorld: typeof import('./components/DF.md')['default']
    IIonAndroidContact: typeof import('~icons/ion/android-contact')['default']
    IMdiAccountCard: typeof import('~icons/mdi/account-card')['default']
    IMdiAccountReactivate: typeof import('~icons/mdi/account-reactivate')['default']
    MyEditor: typeof import('./components/MyEditor/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
