// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACard: typeof import('ant-design-vue/es')['Card']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ArticleCard: typeof import('./components/ArticleCard/index.vue')['default']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    Logo: typeof import('./components/Logo/index.vue')['default']
    NavCard: typeof import('./components/NavCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    UserInfo: typeof import('./components/UserInfo/index.vue')['default']
    UserInfoCard: typeof import('./components/UserInfoCard/index.vue')['default']
    ZrHeader: typeof import('./views/layout/components/ZrHeader.vue')['default']
    ZrMain: typeof import('./views/layout/components/ZrMain.vue')['default']
  }
}
